[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-stepzen"

[context.production.environment]
  STEPZEN_FOLDER = "api"
  STEPZEN_NAME = "with-next"

[template]
  incoming-hooks = ["StepZen"]
